### PR TITLE
removed final from def id in IdTable

### PR DESCRIPTION
**Pull request by Ir1sh**
this fixes the problem I describe in https://github.com/VirtusLab/unicorn/issues/78

### CODE REVIEW

**Comment by Ir1sh** [comment]
Any reason this cant be merged?

**Comment by pdolega** [comment]
@pbatko / @liosedhel guys. Is there anything that prevents us from merging this?

**Comment by liosedhel** [comment]
Hello @Ir1sh. Sorry for the "delay" :/ Do you need this change for this particular unicorn version (1.0.x) with slick 3.1 or can I target the newest master branch (unicorn 1.3.x with slick 3.2) ?

**Comment by Ir1sh** [comment]
both would be good we are still using 1.0.x with our own fork with this change but hope to upgrade 1.3 in the next month, maybe two

**Pull request merged**
