### PR TITLE
removed final from def id in IdTable

### PR DESCRIPTION
**Pull request by MarkRBM**
this is already in the slick 3.1 branch see https://github.com/VirtusLab/unicorn/pull/80 but it never got ported to slick 3.2.  cutting a release with this in it would really help me out (currently trying to use version 1.2.0

### CODE REVIEW

**Comment by MarkRBM** [comment]
Looking at the build failure it does not appear related to this pr

**Comment by explicite** [comment]
@liosedhel / @pbatko maybe you could take a look?

**Comment by liosedhel** [comment]
Yes, we will merge this. Somehow I messed up and didn't port this change to newer slick version. Could you target branch unicorn 1.2.0 with this change? Looking into those test failures, those are somehow connected to the last week slick 1.3.0 release (play 2.6, slick 3.2 and scala 2.11/2.12 cross build) - maybe you are interesting to take a look :)

**Comment by MarkRBM** [comment]
changed the base, let me have a quick look to see if I can make the build fail locally

**Comment by liosedhel** [comment]
You have to rebase on top of v1.2.x-slick-3.2.x instead of resolving conflicts, there will be no conflicts if you will do that properly. Something like this should help:
```
git checkout patch-1
git fetch v1.2.x-slick-3.2.0
git rebase --onto FETCH_HEAD HEAD~
```
If you don't want to bother, let me handle that for you :)

**Comment by liosedhel** [comment]
Sure, let that with me. I will try to apply this change for unicorn 1.2.x and 1.3.x. Thanks :)

**Comment by MarkRBM** [comment]
I reforked and did another pr in case that makes it easier https://github.com/VirtusLab/unicorn/pull/95 there are no conflicts this time at least.  what is the preference? branch of master and rebase for each release or branch off the release you want to change?  if you prefer the other pr I can close this one

**Pull request closed without merging**
