### PR TITLE
table id should not be final

### PR DESCRIPTION
**Pull request by MarkRBM**

### CODE REVIEW

**Comment by MarkRBM** [comment]
`sbt scalastyle clean coverage test unidoc "project unicorn-core" +test` passes locally for me so not sure how to recreate the build failure

**Comment by liosedhel** [comment]
Right, one flaky test, unfortunately. Merging.

**Comment by MarkRBM** [comment]
awesome thanks, when might this get onto sonatype?

**Comment by liosedhel** [comment]
Should be now, version 1.2.1. Enjoy! (Although sonatype is super slow today, so you might need to wait till tomorrow).

**Pull request merged**
